#!/usr/bin/env bash
# Install nginx on web-01 server listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo '<html><body>Hello World!</body></html>' > /var/www/html/index.html
sudo service nginx start
sudo service nginx reload
