#!/usr/bin/env bash

# Configure Nginx to include a custom header (X-Served-By) in its HTTP response
hostname=$(hostname)
nginx_config_file="/etc/nginx/sites-available/default"

# Install Nginx if not already installed
apt-get update -y
apt-get install nginx -y

# Create a basic HTML file
echo "Hello World!" > /usr/share/nginx/html/index.html

# Create a custom 404 page
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx to include the custom header
nginx_config=$(cat <<EOF
server {
    add_header X-Served-By $hostname;
    # other server configurations...
}
EOF
)

echo "$nginx_config" > "$nginx_config_file"

# Restart Nginx to apply the changes
service nginx restart
