#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
frontend app
        bind *:80
        mode http
        default_backend webservers

backend webservers
        mode http
        balance roundrobin
        server web-01 35.153.50.156:80 check
        server web-02 100.25.203.149:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
